@startuml

package engine {
    abstract class GameController {
        # Monde monde
        --
        + {abstract} update(long): void
    }

    abstract class Engine {
        + Engine(ui, controller)
        + {abstract} start(): void
        + {abstract} stop(): void
        + {abstract} tick(long): void
    }

    interface GameInterface {
        + render(): void
    }
}

package cli {
    class CLIController {
        + start(): void
        + stop(): void
        + update(long): void
    }

    class CLIEngine {
        + start(): void
        + stop(): void
        + tick(long): void
    }

    class CLI {
        + render(): void
    }
}

package gui {
    abstract class View {
        # Parent root
        --
        + getRoot(): Parent
        + enableRootEvents(): void
        + onViewInit(): void
        + onViewDisplayed(): void
        + onKeyPressed(KeyEvent): void
        + onKeyReleased(KeyEvent): void
    }

    abstract class ViewController {}

    enum VIEWS {
        HOME
        GAME
    }

    class ViewManager {
        - {static} instance: ViewManager
        - stage: Stage
        --
        - ViewManager()
        + {static} getInstance(): ViewManager
        + setStage(Stage): void
        + registerView(VIEWS, View): void
        + navigateTo(VIEWS): void
        + setFullScreen(boolean): void
    }

    package views {
        class HomeViewController {
            - gameTitle: String
            - fullScreenCheckBox: CheckBox
            --
            # onButtonClick(): void
            # onFullScreenToggle(): void
            + setGameTitle(String): void
            + setFullScreenCheckBox(boolean): void
        }

        class GameViewController {
            - canvas: Canvas
            --
            + getCanvas(): Canvas
        }

        class HomeView {
            + HomeView()
            + onViewInit(): void
            + onKeyPressed(KeyEvent): void
        }

        class GameView {
            + GameView()
            + onViewDisplayed(): void
            - draw(Canvas, Number): void
            + render(): void
        }
    }

    class Sprite {
        - String uri
        + Sprite(uri)
    }

    package engine {
        class GUIController {
            + update(long): void
        }

        class GUIEngine {
            - AnimationTimer timer
            --
            + tick(long): void
            + start(): void
            + stop(): void
            + getComputedFPS(): int
            + getFPS(): int
        }
    }
}

' engine
Engine -left-"1" GameInterface : # ui
Engine -right-"1" GameController : # controller

' cli
CLIController -down-|> GameController
CLIEngine -down-|> Engine
CLI .down.|> GameInterface
CLI -right-"1" CLIController : - controller
CLI -right-"1" CLIEngine : - engine

' gui
GUIController -up-|> GameController
GUIEngine -up-|> Engine
GameView .up.|> GameInterface
GameView --"1" GUIController : - controller
GameView --"1" GUIEngine : - engine
GUIEngine -down[hidden]- GUIController

View --"1" ViewController : # controller
ViewManager -"*" View : - views

' gui views
HomeViewController -up-|> ViewController
HomeView -up-|> View
GameViewController -up-|> ViewController
GameView -up-|> View

@enduml
